services:
  - type: worker
    name: MyService
    env: node
    region: frankfurt
    buildCommand: pnpm install
    startCommand: pnpm start
    repo: https://github.com/knandersen/slackgpt.git
    branch: main
    plan: free
    envVars:
    - key: SLACK_APP_TOKEN
      sync: false # placeholder
    - key: SLACK_BOT_TOKEN
      sync: false
    - key: OPENAI_API_KEY
      sync: false